### ISSUE TITLE
Favorite Icon + GCS

### ISSUE THREAD

**Issue by safaci2000** [OSAlt/gb-www-site#1]
When using google storage the favicon is not loading as expected.

```sh
beta_site_1  | GhostGCSAdapterError: Ghost GCS Adapter Error: No such object: gb-www-geekbeacon/https:/storage.googleapis.com/gb-www-geekbeacon/2021/03/0090a2b1dfbfdaf5.png
beta_site_1  |     at PassThrough.<anonymous> (/var/lib/ghost/content/adapters/storage/gcs/index.js:277:24)
beta_site_1  |     at PassThrough.emit (events.js:314:20)
beta_site_1  |     at PassThrough.EventEmitter.emit (domain.js:483:12)
beta_site_1  |     at emitErrorNT (internal/streams/destroy.js:92:8)
beta_site_1  |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
beta_site_1  |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by safaci2000** [comment]
Fixed via nginx config.

        location /favicon.png {
          alias /var/www/html/geekbeacon/favicon.png;
          allow all;
       }
